controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Pacientes;
use yii\data\ActiveDataProvider;
use yii\db\ActiveQuery;
use app\models\Auxiliares;
use app\models\Telefonos;
use app\models\Deposiciones;
use app\models\Revisiones;
use app\models\Rellenados;
use app\models\Menstruaciones;
use app\models\Partes;
use app\models\Habitaciones;
use app\models\Camas;





class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
     public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
       $this->layout = 'logins'; // Asignar el layout específico

        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);

    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }


    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
    
    
public function actionMostrarpacientes()
{
    $dataProvider = new ActiveDataProvider([
        'query' => Pacientes::find()->orderBy(['nombreCompleto' => SORT_ASC]), // Ordena por nombre completo en orden ascendente
        'pagination' => [
            'pageSize' => 9, // Ajusta según sea necesario
        ],
    ]);

    return $this->render('pacientes2', [
        'dataProvider' => $dataProvider,
    ]);
}

    
    public function actionRegistros()
    {
    return $this->render('registros'); // Este es el nombre de la vista en el archivo 'registros.php'
    }
    
public function actionVerprotocolos($pdfName) {
    // Ruta al directorio donde se almacenan los archivos PDF
    $pdfDirectory = Yii::getAlias('@webroot') . '/documentos/';

    // Ruta completa al archivo PDF
    $pdfPath = $pdfDirectory . $pdfName;

    // Verificar si el archivo existe
    if (file_exists($pdfPath)) {
        // Devolver el contenido del PDF al navegador
        return Yii::$app->response->sendFile($pdfPath, $pdfName, ['inline' => true]);
    } else {
        // Manejar el caso en que el archivo no existe
        throw new \yii\web\NotFoundHttpException('El archivo PDF no se encuentra.');
    }
}

public function actionVerprotocolorcp() {
    return $this->actionVerprotocolos('rcp.pdf');
}

public function actionVerprotocoloatragantamiento() {
    return $this->actionVerprotocolos('Atragantamiento.pdf');
}

public function actionVerprotocolocontencion() {
    return $this->actionVerprotocolos('Protocolo-contencion.pdf');
}

public function actionVerprotocolomovilizacion() {
    return $this->actionVerprotocolos('Movilizacion.pdf');
}


  public function actionProtocolos()
    {
    return $this->render('protocolos'); // Este es el nombre de la vista en el archivo 'registros.php'
    }
    
     public function actionTecnicos()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Auxiliares::find()->with('telefonos'),
            'pagination' => [
            'pageSize' => 10, // Número de registros por página
        ],
        ]);

        return $this->render('tecnicos', [
            'dataProvider' => $dataProvider,
        ]);
    }
    
//    public function actionEditarpaciente($id)
//{
//    $model = $this->findModel($id);
//
//    if ($model->load(Yii::$app->request->post()) && $model->save()) {
//        return $this->redirect(['view', 'id' => $model->id]);
//    }
//
//    return $this->render('edit', [
//        'model' => $model,
//    ]);
//}
    
public function actionRegistrospartes($pacienteId) {
    Yii::info("ID del paciente: $pacienteId", 'app.controller');

    // Obtener el primer y último día del mes actual
    $startDate = date('Y-m-01');
    $endDate = date('Y-m-t');

    // Buscar el modelo del paciente
    $pacienteModel = Pacientes::findOne($pacienteId);

    // Obtener los DataProviders para los registros de deposiciones filtrados por el mes actual
    $dataProviderDeposiciones = new ActiveDataProvider([
        'query' => Deposiciones::find()
            ->where(['idPacientes' => $pacienteId])
            ->andWhere(['>=', 'fecha', $startDate])
            ->andWhere(['<=', 'fecha', $endDate]),
    ]);

    // Obtener los DataProviders para los registros de menstruaciones filtrados por el mes actual
    $dataProviderMenstruaciones = new ActiveDataProvider([
        'query' => Menstruaciones::find()
            ->where(['idPacientes' => $pacienteId])
            ->andWhere(['>=', 'fecha', $startDate])
            ->andWhere(['<=', 'fecha', $endDate]),
    ]);

    // Obtener los DataProviders para los registros de revisiones filtrados por el mes actual
    $dataProviderRevisiones = new ActiveDataProvider([
        'query' => Revisiones::find()
            ->where(['idPacientes' => $pacienteId])
            ->andWhere(['>=', 'fechaManos', $startDate])
            ->andWhere(['<=', 'fechaManos', $endDate])
            ->andWhere(['>=', 'fechaPies', $startDate])
            ->andWhere(['<=', 'fechaPies', $endDate]),
    ]);

// Obtener los DataProviders para los registros de partes filtrados por el mes actual
$dataProviderPartes = new ActiveDataProvider([
    'query' => Partes::find()
        ->select(['partes.id', 'rellenados.fecha', 'rellenados.turno', 'partes.descripcion'])
        ->innerJoinWith('rellenados')
        ->where(['rellenados.idPacientes' => $pacienteId])
        ->andWhere(['>=', 'rellenados.fecha', $startDate])
        ->andWhere(['<=', 'rellenados.fecha', $endDate]),
]);

    // Renderizar la vista y pasar los DataProviders junto con el modelo del paciente
    return $this->render('registrosPartes', [
        'model' => $pacienteModel,
        'dataProviderDeposiciones' => $dataProviderDeposiciones,
        'dataProviderMenstruaciones' => $dataProviderMenstruaciones,
        'dataProviderRevisiones' => $dataProviderRevisiones,
        'dataProviderPartes' => $dataProviderPartes,
        'pacienteId' => $pacienteId,
    ]);
}



    
public function actionCreardeposicion($pacienteId)
{
    // Buscar el modelo del paciente
    $pacienteModel = Pacientes::findOne($pacienteId);

    // Crear una nueva instancia del modelo de Deposiciones
    $model = new Deposiciones();
    $model->idPacientes = $pacienteId;

    // Determinar la hora actual
    $horaActual = date('H');

    // Definir el valor predeterminado para el campo "turno" en función de la hora actual
    if ($horaActual >= 8 && $horaActual < 15) {
        $turnoPredeterminado = 'Mañana';
    } elseif ($horaActual >= 15 && $horaActual < 22) {
        $turnoPredeterminado = 'Tarde';
    } else {
        $turnoPredeterminado = 'Noche';
    }

    // Verificar si se ha enviado el formulario y se ha guardado correctamente el modelo
    if ($model->load(Yii::$app->request->post())) {
        // Formatear la fecha antes de guardar
        $model->fecha = date('Y-m-d', strtotime($model->fecha));

        if ($model->save()) {
            Yii::$app->session->setFlash('success', 'Deposición creada correctamente.');
            // Redirigir a la vista de detalles del paciente con el ID del paciente
            return $this->redirect(['site/registrospartes', 'pacienteId' => $pacienteId]);
        }
    }

    // Renderizar el formulario con el modelo de deposiciones y el modelo del paciente
    return $this->render('formulariodeposiciones', [
        'model' => $model,
        'nombrePaciente' => $pacienteModel->nombreCompleto, // Pasar el nombre del paciente a la vista
        'turnoPredeterminado' => $turnoPredeterminado, // Pasar el turno predeterminado a la vista
    ]);
}



    
 public function actionCrearmenstruacion($pacienteId)
{
    $pacienteModel = Pacientes::findOne($pacienteId);
    $model = new Menstruaciones(['idPacientes' => $pacienteId]);

    if ($model->load(Yii::$app->request->post())) {

views/site/alertasMenstruaciones.php
<?php
use yii\helpers\Html;

$this->title = 'Alertas de Menstruaciones';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="card mb-4"> <!-- Agregado mb-4 para añadir margen inferior -->
    <div class="card-body text-center"> <!-- Centrado del texto -->
        <h4 class="card-title">Incidencias de menstruaciones</h4>
    </div>
</div>

<?php if (!empty($alertasMenstruaciones)) : ?>
    <div class="alert alert-warning card" role="alert">
        <h4 class="alert-heading">Avisar a la enfermera</h4>
        <p>Los siguientes pacientes han presentado sangrado durante más de 7 días consecutivos:</p>
        <ul>
            <?php foreach ($alertasMenstruaciones as $paciente) : ?>
                <li><?= Html::encode($paciente['nombre']) ?></li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php else : ?>
    <div class="alert alert-info card" role="alert">
        No hay incidencias de menstruaciones en este momento.
    </div>
<?php endif; ?>

views/site/alertaspeso.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Alertas peso';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="card mb-4"> <!-- Agregado mb-4 para añadir margen inferior -->
    <div class="card-body text-center"> <!-- Centrado del texto -->
        <h4 class="card-title">Incidencias del IMC</h4>
    </div>
</div>

views/site/error.php
<?php

/** @var yii\web\View $this */
/** @var string $name */
/** @var string $message */
/** @var Exception$exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/formularioMenstruaciones.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Formilario de menstruaciones';
$this->params['breadcrumbs'][] = ['label' => 'Pacientes', 'url' => ['/site/mostrarpacientes']];
$this->params['breadcrumbs'][] = $this->title;

$form = ActiveForm::begin(); ?>

<div class="card"> <!-- Agregar una clase de Bootstrap para la caja -->
    <div class="card-body"> <!-- Agregar una clase de Bootstrap para el cuerpo de la caja -->
        <h3>Nuevo registro de menstruaciones</h3> <!-- Agregar el título dentro del cuerpo de la caja -->
    </div>
</div>

<?= $form->field($model, 'idPacientes')->hiddenInput()->label(false) ?>

<div>
    <label class="control-label">Nombre del Paciente</label>
    <h3><?= Html::encode($nombrePaciente) ?></h3>
</div>

<?= $form->field($model, 'fecha')->textInput(['value' => Yii::$app->formatter->asDate(date('Y-m-d'), 'php:d-m-Y'), 'readonly' => true]) ?>


<?= $form->field($model, 'positivo')->radioList([
    '1' => 'Sí',
    '0' => 'No'
])->label(false) ?>
<div id="errorMensaje" style="display: none; color: red;">Debes seleccionar "Sí" o "No".</div>

<div class="form-group">
    <?= Html::submitButton('Guardar', ['class' => 'btn btn-success', 'id' => 'guardarButton']) ?>
</div>

<?php ActiveForm::end(); ?>

<?php
$js = <<<JS
$('#guardarButton').click(function(event) {
    event.preventDefault(); // Evitar el envío predeterminado del formulario
    // Verificar si se ha seleccionado "Sí" o "No"
    var seleccionado = $('input[name="Menstruaciones[positivo]"]:checked').val();
    if (seleccionado === '1' || seleccionado === '0') {
        $('#confirmacionModal').modal('show'); // Mostrar el modal de confirmación si se ha seleccionado "Sí" o "No"
        $('#errorMensaje').hide(); // Ocultar el mensaje de error si estaba mostrándose
    } else {
        // Si no se ha seleccionado "Sí" o "No", mostrar el mensaje de error
        $('#errorMensaje').show(); // Mostrar el mensaje de error
    }
});

// Evento de click para el botón de guardar dentro del modal de confirmación
$('#confirmarGuardar').click(function() {
    $('#confirmacionModal').modal('hide'); // Ocultar el modal de confirmación
    $('form').submit(); // Enviar el formulario
});
JS;
$this->registerJs($js);
?>

<!-- Modal de confirmación -->
<div class="modal fade" id="confirmacionModal" tabindex="-1" role="dialog" aria-labelledby="confirmacionModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-vertical-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="confirmacionModalLabel">Confirmación</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Cerrar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                ¿Estás seguro de querer guardar este registro de menstruaciones? No podrás editar ni borrar después de guardar.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary" id="confirmarGuardar">Guardar</button>
            </div>
        </div>
    </div>
</div>

views/site/formularioPartes.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Formulario de partes';
$this->params['breadcrumbs'][] = ['label' => 'Pacientes', 'url' => ['/site/mostrarpacientes']];
$this->params['breadcrumbs'][] = $this->title;

$form = ActiveForm::begin(); ?>

<div class="card">
    <div class="card-body">
        <h3>Nuevo registro de partes</h3>
    </div>
</div>

<?= $form->field($model, 'idPacientes')->hiddenInput(['value' => $pacienteId])->label(false) ?>

<div>
    <label class="control-label">Nombre del Paciente</label>
    <h3><?= Html::encode($nombrePaciente) ?></h3>
</div>

<?= $form->field($modelRellenado, 'idAuxiliares')->dropDownList(
    \yii\helpers\ArrayHelper::map($auxiliares, 'id', 'nombreAuxiliar'),
    ['prompt' => 'Seleccionar un auxiliar']
) ?>

<?= $form->field($model, 'fecha')->textInput(['value' => Yii::$app->formatter->asDate(date('Y-m-d'), 'php:d-m-Y'), 'readonly' => true]) ?>

<?= $form->field($modelRellenado, 'turno')->textInput(['value' => $turnoPredeterminado, 'readonly' => true]) ?>

<?= $form->field($model, 'descripcion')->widget(\mihaildev\ckeditor\CKEditor::className(), [
    'editorOptions' => [
        'height' => 'auto',
        'inline' => false,
    ],
]) ?>

<div class="form-group">
    <?= Html::button('Guardar', ['class' => 'btn btn-success', 'id' => 'guardarButton']) ?>
</div>

<?php ActiveForm::end(); ?>

<?php
$js = <<<JS
$('#guardarButton').click(function() {
    $('#confirmacionModal').modal('show');
});

$('#confirmarGuardar').click(function() {
    $('#confirmacionModal').modal('hide');
    $('form').submit();
});
JS;
$this->registerJs($js);
?>

<div class="modal fade" id="confirmacionModal" tabindex="-1" role="dialog" aria-labelledby="confirmacionModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-vertical-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="confirmacionModalLabel">Confirmación</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Cerrar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                ¿Estás seguro de querer guardar? No podrás editar ni borrar después de guardar.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary" id="confirmarGuardar">Guardar</button>
            </div>
        </div>
    </div>
</div>

views/site/formularioRevisiones.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Formulario de revisiones';
$this->params['breadcrumbs'][] = ['label' => 'Pacientes', 'url' => ['/site/mostrarpacientes']];
$this->params['breadcrumbs'][] = $this->title;

$form = ActiveForm::begin(); ?>

<div class="card">
    <div class="card-body">
        <h3>Nuevo registro de revisiones</h3>
    </div>
</div>

<?= $form->field($model, 'idPacientes')->hiddenInput(['value' => $pacienteId])->label(false) ?>

<div>
    <label class="control-label">Nombre del Paciente</label>
    <h3><?= Html::encode($nombrePaciente) ?></h3>
</div>

<?= $form->field($model, 'fechaManos')->textInput(['value' => date('d-m-Y'), 'readonly' => true]) ?>

<?= $form->field($model, 'manos')->radioList([
    '1' => 'Sí',
    '0' => 'No'
])->label(false) ?>

<?= $form->field($model, 'fechaPies')->textInput(['value' => date('d-m-Y'), 'readonly' => true]) ?>

<?= $form->field($model, 'pies')->radioList([
    '1' => 'Sí',
    '0' => 'No'
])->label(false) ?>

<div id="errorMensaje" style="display: none; color: red;">Debes seleccionar "Sí" o "No".</div>

<?= $form->field($model, 'observacion')->widget(\mihaildev\ckeditor\CKEditor::className(), [
    'editorOptions' => [
        'height' => 'auto',
        'inline' => false,
    ],
]) ?>

<div class="form-group">
    <?= Html::submitButton('Guardar', ['class' => 'btn btn-success', 'id' => 'guardarButton']) ?>
</div>

<?php ActiveForm::end(); ?>

<?php
$js = <<<JS
$('#guardarButton').click(function(event) {
    event.preventDefault(); // Evitar el envío predeterminado del formulario

    // Verificar si se ha seleccionado "Sí" o "No" para ambos campos radio
    var manosSeleccionado = $('input[name="Revisiones[manos]"]:checked').val();
    var piesSeleccionado = $('input[name="Revisiones[pies]"]:checked').val();

    if ((manosSeleccionado === '1' || manosSeleccionado === '0') && (piesSeleccionado === '1' || piesSeleccionado === '0')) {
        $('#confirmacionModal').modal('show'); // Mostrar el modal de confirmación si ambos campos están seleccionados
        $('#errorMensaje').hide(); // Ocultar el mensaje de error si estaba mostrándose
    } else {
        // Si no se ha seleccionado "Sí" o "No" en ambos campos, mostrar el mensaje de error
        $('#errorMensaje').show(); // Mostrar el mensaje de error
    }
});

// Evento de click para el botón de guardar dentro del modal de confirmación
$('#confirmarGuardar').click(function() {
    $('#confirmacionModal').modal('hide'); // Ocultar el modal de confirmación
    $('form').submit(); // Enviar el formulario
});
JS;
$this->registerJs($js);
?>

<div class="modal fade" id="confirmacionModal" tabindex="-1" role="dialog" aria-labelledby="confirmacionModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-moved-down" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="confirmacionModalLabel">Confirmación</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Cerrar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                ¿Estás seguro de querer guardar este registro de revisiones? No podrás editar ni borrar después de guardar.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary" id="confirmarGuardar">Guardar</button>
            </div>
        </div>
    </div>
</div>

views/site/historialDeposiciones.php
<?php
use yii\grid\GridView;
use yii\helpers\Html;

$this->title = 'Historial de registros de ' . $model->nombreCompleto;
$this->params['breadcrumbs'][] = ['label' => 'Pacientes', 'url' => ['/site/mostrarpacientes']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="card mb-4"> <!-- Agregado mb-4 para añadir margen inferior -->
    <div class="card-body text-center"> <!-- Centrado del texto -->
        <h4 class="card-title">Historial de deposiciones</h4>
    </div>
</div>
<div>
    <label class="control-label">Nombre del Paciente</label>
    <h3><?= Html::encode($model->nombreCompleto) ?></h3>
</div>
<br><br>

<div id="partes-table">
<?= GridView::widget([
    'dataProvider' => $dataProviderDeposiciones,
    'columns' => [
        'turno',
        [
            'attribute' => 'fecha',
            'format' => ['date', 'php:d-m-Y'], // Aquí se define el formato día-mes-año
        ],
        'positivo:boolean', // Cambia a boolean si 'positivo' es un campo booleano
    ],
    'pager' => [
        'options' => ['class' => 'pagination'],
        'hideOnSinglePage' => true,
        'nextPageLabel' => 'Siguiente',
        'prevPageLabel' => 'Anterior',
    ],
    'summary' => false,
]); ?>
</div>

views/site/historialRevisiones.php
<?php
use yii\grid\GridView;
use yii\helpers\Html;

$this->title = 'Historial de registros de ' . $model->nombreCompleto;
$this->params['breadcrumbs'][] = ['label' => 'Pacientes', 'url' => ['/site/mostrarpacientes']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="card mb-4"> <!-- Agregado mb-4 para añadir margen inferior -->
    <div class="card-body text-center"> <!-- Centrado del texto -->
        <h4 class="card-title">Historial de revisiones</h4>
    </div>
</div>

<div>
    <label class="control-label">Nombre del Paciente</label>
    <h3><?= Html::encode($model->nombreCompleto) ?></h3>
</div>
<br><br>

<div id="partes-table">
<?= GridView::widget([
    'dataProvider' => $dataProviderRevisiones,
    'columns' => [
        [
            'attribute' => 'fechaManos',
            'format' => ['date', 'php:d-m-Y'],
        ],
        'manos',
        [
            'attribute' => 'fechaPies',
            'format' => ['date', 'php:d-m-Y'],
        ],
        'pies',
        'observacion:html',
    ],
    'pager' => [
        'options' => ['class' => 'pagination'],
        'hideOnSinglePage' => true,
        'nextPageLabel' => 'Siguiente',
        'prevPageLabel' => 'Anterior',
    ],
    'summary' => false,
]); ?>
</div>

views/site/todasRevisiones.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\LinkPager;

$this->title = 'Todas las Revisiones de Manos y Pies';
$this->params['breadcrumbs'][] = ['label' => 'Registros', 'url' => ['/site/registros']];
$this->params['breadcrumbs'][] = $this->title;

// Registra tu archivo CSS personalizado
$this->registerCssFile('@web/css/custom-styles.css');

// Incluye tu script JavaScript
$script = <<<JS
document.addEventListener('DOMContentLoaded', function() {
    // Encuentra todos los enlaces dentro del contenedor de paginación y les aplica la clase btn-custom
    document.querySelectorAll('.pagination a').forEach(function(element) {
        element.classList.add('btn-custom');
    });
});
JS;

// Registra el script en la vista
$this->registerJs($script, \yii\web\View::POS_READY);
?>

<div class="card mb-4"> <!-- Agregado mb-4 para añadir margen inferior -->
    <div class="card-body text-center"> <!-- Centrado del texto -->
        <h4 class="card-title">Historial de revisiones de todos los pacientes</h4>
    </div>
</div>


<?= GridView::widget([
    'dataProvider' => $dataProvider,
    'columns' => [
        [
            'attribute' => 'idPacientes',
            'label' => 'Paciente',
            'value' => function ($model) {
                return $model->idPacientes0->nombreCompleto;
            },
        ],
        [
            'attribute' => 'manos',
            'label' => 'Revisión de Manos',
            'value' => function ($model) {
                return $model->manos ? 'Sí' : 'No';
            },
        ],
        [
            'attribute' => 'fechaManos',
            'label' => 'Fecha Revisión Manos',
        ],
        [
            'attribute' => 'pies',
            'label' => 'Revisión Pies',
            'value' => function ($model) {
                return $model->pies ? 'Sí' : 'No';
            },
        ],
        [
            'attribute' => 'fechaPies',
            'label' => 'Fecha Revisión Pies',
        ],
        [
            'attribute' => 'observacion',
            'format' => 'html',
            'value' => function($model) {
                return $model->observacion;
            },
        ],
    ],
    'layout' => "{items}", // Elimina la paginación y el resumen de la tabla
    'options' => [
        'class' => 'table table-bordered table-striped',
    ],
    'summary' => false,
]) ?>

<div class="row">
    <div class="col-sm-12 text-center"> <!-- Centra la paginación -->
        <!-- Paginación -->
        <?= LinkPager::widget([
            'pagination' => $dataProvider->pagination,
            'nextPageLabel' => 'Siguiente',
            'prevPageLabel' => 'Anterior',
            'maxButtonCount' => 5, 
            'options' => ['class' => 'pagination justify-content-center pagination-container'], 
            'linkOptions' => ['class' => 'page-link'], 
            'activePageCssClass' => 'active', 
            'pageCssClass' => 'page-item', 
            'hideOnSinglePage' => true,
        ]); ?>
    </div>
</div>